Web socket for java
shvshv44/MultiPlayerQuoridor-RL pull request #15
Opened 2020-12-17 13:44 UTC by RavivGuy

2020-12-17 16:38 UTC, Guyeise1 requested changes
There are lots of files here that I have different PR with some changes.
Those files should not be a part of this PR.

2020-12-17 16:38 UTC, Guyeise1 commented on quoridor-logic-server/src/main/java/com/rl/mpquoridor/controllers/GameWebSocket.java
> +    @MessageMapping("/movePawn/{gameId}")
The order should be opposite.
{gameId}/movePawn

or if its not possible then
/game/{gameId}/movePawn

2020-12-17 16:38 UTC, Guyeise1 commented on quoridor-logic-server/src/main/java/com/rl/mpquoridor/controllers/GameWebSocket.java
> +    public void movePawn(@PathVariable String gameId, TurnAction action) {
TurnAction -> MovePawn

2020-12-17 16:38 UTC, Guyeise1 commented on quoridor-logic-server/src/main/java/com/rl/mpquoridor/controllers/GameWebSocket.java
> +    public void putWall(@PathVariable String gameId, TurnAction action) {
TurnAction -> PlaceWall

2020-12-17 18:19 UTC, shvshv44 commented on quoridor-logic-server/src/main/java/com/rl/mpquoridor/models/GameResult.java
> +    private final List<Pair<Player, TurnAction>> history;
I think its more clean to make 'Pair' field into a pojo contains two fields.
history could be of type PlayerTurnData, or HistoryMove or something with the same context

2020-12-17 18:20 UTC, shvshv44 commented on quoridor-logic-server/src/main/java/com/rl/mpquoridor/models/GameResult.java
> +    public Player getWinner() {
You could use Lombok like Sharon did.
Its working fine with pojos

2020-12-18 09:07 UTC, SharonEizner commented on quoridor-logic-server/src/main/java/com/rl/mpquoridor/controllers/GameWebSocket.java
> +        // send the available moves of the next turn
i dont think that u need to send this. 
in the client u have basic validation, and in the server u will get error message if u cant put the wall

2020-12-21 20:28 UTC, shvshv44 approved these changes

2020-12-25 20:36 UTC, shvshv44 approved these changes

2020-12-25 20:41 UTC, SharonEizner approved these changes

2020-12-25 20:41 UTC, shvshv44 approved these changes

2020-12-25 20:43 UTC, shvshv44 approved these changes

2020-12-25 20:45 UTC, shvshv44 approved these changes

2020-12-25 20:45 UTC, merged