Controlling with rest new try
shvshv44/MultiPlayerQuoridor-RL pull request #69
Opened 2021-04-15 14:49 UTC by shvshv44

2021-04-15 20:23 UTC, Guyeise1 requested changes

2021-04-15 20:23 UTC, Guyeise1 commented on client/src/assets/config.json
> +  "serverUrl": "http://localhost:8080",
Revert this

2021-04-16 09:16 UTC, SharonEizner approved these changes

2021-04-16 12:19 UTC, Guyeise1 approved these changes

2021-04-17 12:05 UTC, merged